services:
  pygeoapi:
    image: geopython/pygeoapi:latest                # 'Sti' til image. Vi bruker 'latest' versjon her, men det er ofte lurt 책 spesifisere med versjonsnummer
    container_name: pygeoapi                        # valgfritt, men det er fint 책 sette eget container navn
    ports:
      - "5000:80"                                 # Her 'mappes' port 80 i containeren med port 5000 p책 pc'en din
    restart: unless-stopped                         # Containeren restarter seg selv, med mindre den f책r en stopp-kommando. Eks. 'docker compose down'