server:
  bind:
    host: 0.0.0.0
    port: 5000
  cors: true
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en
  pretty_print: true
  limits:
    default_items: 15
    max_items: 1000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  admin: false

logging:
  level: INFO

metadata:
  identification:
    title: Administrative enheter
    description:
      en: Datasettet inneholder administrative grenser og omr√•der for Norge, inkludert fylker og kommuner.
    keywords:
      - Fylke
      - Kommune
      - Administrativ inndeling
      - Administrative grenser
      - Fylkesgrenser
      - Kommunegrenser
      - Riksgrense
    keywords_type: theme
    terms_of_service: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
    url: https://www.kartverket.no

  license:
    name: Norge digitalt-lisens
    url: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
  provider:
    name: Kartverket
    url: https://www.kartverket.no
  contact:
    name: Kartverket
    email: post@kartverket.no
    url: https://www.kartverket.no

resources:
  fylker:
    type: collection
    title: Fylker
    description: Din kule beskrivelse av fylker
    keywords:
      en:
        - Fylke
        - Fylkesgrense
    extents:
      spatial:
        bbox: [4.626095, 57.977101, 31.125157, 71.188325]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    # links:
    #   - type: text/html
    #     rel: related
    #     title: Geonorge link
    #     href: https://kartkatalog.geonorge.no/metadata/administrative-enheter-fylker/6093c8a8-fa80-11e6-bc64-92361f002671
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${POSTGRES_HOST}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          search_path: [administrative_enheter_fylker]
        id_field: objid
        table: fylke
        geom_field: omrade
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833 # Datene vi har i databasen er lagret i koordinatsystemet EPSG:25833
  kommuner:
    type: collection
    title: Kommuner
    description: Din kule beskrivelse av kommuner
    keywords:
      en:
        - Kommune
        - Kommunegrenser
    extents:
      spatial:
        bbox: [4.626095, 57.977101, 31.125157, 71.188325]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    # links:
    #   - type: text/html
    #     rel: related
    #     title: Geonorge link
    #     href: https://kartkatalog.geonorge.no/metadata/administrative-enheter-kommuner/041f1e6e-bdbc-4091-b48f-8a5990f3cc5b
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${POSTGRES_HOST}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          search_path: [administrative_enheter_kommuner]
        id_field: objid
        table: kommune
        geom_field: omrade
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833 # Datene vi har i databasen er lagret i koordinatsystemet EPSG:25833
